[theme]
primaryColor = "#667eea"
backgroundColor = "#f0f0f0"
secondaryBackgroundColor = "#f9f9f9"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "auto"

[logger]
level = "info"
